Periodic Update.
Changelog:
  - Updated package lists.
  - Improved and fixed privsetup timer functionality.
  - Removed "chat" script in favor of ollama.

diff --git a/local-bin/privsetup b/local-bin/privsetup
--- a/local-bin/privsetup
+++ b/local-bin/privsetup
@@ -3,79 +3,88 @@
 # Sets POSIX strict mode
 set -eu
 
-TARGET_USER="nikut"
-DEVICE="/dev/nvme0n1p2"
-MAPPER_NAME="priv"
-UNMOUNT_AFTER=600   # 10 minutes
-
-TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
-MOUNT_POINT="$TARGET_HOME/Private"
-
 # Ensure script is run as root
 if [ "$(id -u)" -ne 0 ]; then
     echo "Missing required super-user permissions." >&2
     exit 1
 fi
 
+# Ensure valid configuration file
+if [ ! -f ~/.privsetup_env ]; then
+    echo "$0: Missing required configuration file: ~/.privsetup_env"
+    exit 1
+fi
+
+# Reads $user, $device and $mapper
+. ~/.privsetup_env
+
+home="$(getent passwd "$user" | cut -d: -f6)"
+mount_point="$home/Private"
+default_timeout=10   # 10 minutes
+
 privclose() {
     # Stops any timers that are still running
     systemctl stop 'privsetup-autoclose-*.timer'
 
-    if ! mountpoint -q "$MOUNT_POINT"; then
-        echo "$MOUNT_POINT is not mounted." >&2
+    if ! mountpoint -q "$mount_point"; then
+        echo "$mount_point is not mounted." >&2
         return 1
     fi
 
     # Unmounts the mapped LUKS container
-    umount "$MOUNT_POINT"
+    umount "$mount_point"
 
     # Resets the ownership of the container
-    chown root:root "$MOUNT_POINT"
+    chown root:root "$mount_point"
 
     # Closes the LUKS container if still active
-    if cryptsetup status "$MAPPER_NAME" >/dev/null 2>&1; then
-        cryptsetup close "$MAPPER_NAME"
+    if cryptsetup status "$mapper" >/dev/null 2>&1; then
+        cryptsetup close "$mapper"
     fi
 
     echo "-> Unmounted successfully!"
 }
 
 privopen() {
-    if mountpoint -q "$MOUNT_POINT"; then
-        echo "$MOUNT_POINT is already mounted." >&2
+    if mountpoint -q "$mount_point"; then
+        echo "$mount_point is already mounted." >&2
         return 1
     fi
 
     # Opens the LUKS container
-    echo "Opening LUKS container $DEVICE..."
-    cryptsetup open "$DEVICE" "$MAPPER_NAME"
+    echo "Opening LUKS container $device..."
+    cryptsetup open "$device" "$mapper"
 
     # Mounts the mapped LUKS container
-    echo "Mounting /dev/mapper/$MAPPER_NAME on $MOUNT_POINT..."
-    mount "/dev/mapper/$MAPPER_NAME" "$MOUNT_POINT"
+    echo "Mounting /dev/mapper/$mapper on $mount_point..."
+    mount "/dev/mapper/$mapper" "$mount_point"
 
     # Sets the ownership of the mountpoint
-    echo "Setting ownership of $MOUNT_POINT to $TARGET_USER ..."
-    chown "$TARGET_USER":"$TARGET_USER" "$MOUNT_POINT"
+    echo "Setting ownership of $mount_point to $user ..."
+    chown "$user":"$user" "$mount_point"
 
-    echo "-> Mounted successfully! It will be automatically unmounted in $((UNMOUNT_AFTER / 60)) minutes."
+    # Determines timer duration
+    local timeout=$(("${1:=$default_timeout}" * 60))
 
     # Sets the background job for automatic closing of the container
     systemd-run \
         --unit="privsetup-autoclose-$$" \
-        --on-active="$UNMOUNT_AFTER" \
+        --on-active="$timeout" \
         --service-type=oneshot \
-        /bin/sh -c "$0 close"
+        /bin/sh -c "$(readlink -f $0) close"
+
+    echo "-> Mounted successfully! It will be automatically unmounted in $((timeout / 60)) minutes."
 }
 
 # Main entry point
 option=${1:-}
+timeout=${2:-}
 
 if [ "$option" = "open" ]; then
-    privopen || exit $?
+    privopen "$timeout" || exit $?
 elif [ "$option" = "close" ]; then
     privclose || exit $?
 else
-    echo "Usage: $0 {open|close}" >&2
+    echo "Usage: $0 [open|close] [duration]?" >&2
     exit 2
 fi
